name: drivemate
description: "지방기능경기대회 과제"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - assets/icons/bonnet.svg
    - assets/icons/cancel.svg
    - assets/icons/car_door.svg
    - assets/icons/car_front.svg
    - assets/icons/childseat.svg
    - assets/icons/divide.svg
    - assets/icons/door.svg
    - assets/icons/fan.svg
    - assets/icons/front_car.svg
    - assets/icons/gas_station.svg
    - assets/icons/handle.svg
    - assets/icons/heat.svg
    - assets/icons/image.svg
    - assets/icons/key.svg
    - assets/icons/location.svg
    - assets/icons/lock.svg
    - assets/icons/logo.svg
    - assets/icons/mirror.svg
    - assets/icons/notification.svg
    - assets/icons/number.svg
    - assets/icons/open.svg
    - assets/icons/person.svg
    - assets/icons/power.svg
    - assets/icons/right_arrow.svg
    - assets/icons/setting.svg
    - assets/icons/share.svg
    - assets/icons/side mirror.svg
    - assets/icons/snowflake.svg
    - assets/icons/tailgate.svg
    - assets/icons/warning.svg
    - assets/icons/window.svg
    - assets/icons/weather/cloud.svg
    - assets/icons/weather/rainy.svg
    - assets/icons/weather/rainy_snow.svg
    - assets/icons/weather/snow.svg
    - assets/icons/weather/sunny.svg
    - assets/icons/weather/sunny_snow.svg
    - assets/icons/weather/thunderstorm.svg
    - assets/images/car.webp
    - assets/images/car.png
    - assets/images/red car.png
    - assets/images/cloud1.png
    - assets/images/cloud2.png
    - assets/images/a8.png
    - assets/images/q7.png

  #  - assets/icons/hub_24dp_5F6368_FILL0_wght400_GRAD0_opsz24.svg